name: PilagersEviction
version: '1.6-SNAPSHOT'
main: org.byteexeclab.pilagersEviction.PilagersEviction
api-version: '1.21'
commands:
  pev:
    description: PilagersEviction admin commands
    usage: /pev help
    permission: pilagerseviction.admin
  permissions:
    evictpillagers.admin:
      default: op
libraries:
  - redis.clients:jedis:5.1.3